#!/usr/bin/python

import sys;
import re;
import os;
import subprocess;
import tempfile;

def usage():
    print >>sys.stderr, "Usage: %(prog)s [options] filename.tex" % {'prog': sys.argv[0]};
    exit(255);

if (len(sys.argv) < 2):
    usage();

if (not re.match(r'.*\.(la)?tex', sys.argv[-1])):
    usage();


# find pdflatex
pdflatex = subprocess.Popen("which pdflatex", shell=True, stderr=subprocess.STDOUT,
                            stdout=subprocess.PIPE).communicate()[0].strip();

if (not pdflatex):
    print >>sys.stderr, "Can't find pdflatex!";
    exit(255);
    

texfile = sys.argv[-1];
argv = sys.argv[1:-1];
solutions = False;

runtexfile = None;

workdir = tempfile.mkdtemp();

# see if first flag is "--solutionssheet"
if (argv and argv[0] == "--solutionssheet"):
    solutions = True;
    argv = argv[1:];
    runtexfile = workdir+'/'+re.sub(r'\.((la)?tex)$', r'_sol.\1', texfile);
    try:
        f = open(runtexfile, 'w');
        f.write(r'\def\ethuebungwantsolutions{}\input{'+texfile+'}' +'\n');
        f.close();
    except:
        print >>sys.stderr, "Can't open file %s." % [texfile];
else:
    runtexfile = workdir+'/'+re.sub(r'\.((la)?tex)$', r'_ex.\1', texfile);
    try:
        f = open(runtexfile, 'w');
        f.write(r'\input{'+texfile+'}' +'\n');
        f.close();
    except:
        print >>sys.stderr, "Can't open file %s." % [texfile];

cmd = [pdflatex];
cmd += argv;
cmd += [runtexfile];

e = os.environ;
e['TEXINPUTS'] = os.getcwd()+":"+(e['TEXINPUTS'] if 'TEXINPUTS' in e else '');
e['BIBINPUTS'] = os.getcwd()+":"+(e['BIBINPUTS'] if 'BIBINPUTS' in e else '');

print repr(cmd);
subprocess.call(cmd, env=e);
subprocess.call(cmd, env=e);
exit(subprocess.call(cmd, env=e));
